name: BSP-RPi4

on:
    push:
        branches:
            - master
        paths-ignore:
            - "utils/**"
            - "doc/**"
            - "docker/**"
    pull_request:
        branches:
            - master
        paths-ignore:
            - "utils/**"
            - "doc/**"
            - "docker/**"
    schedule:
        - cron: "0 5 * * *"

jobs:
    build:
        name: Build kernels
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
            - name: Set up Rust tools
              run: |
                  rustup target add aarch64-unknown-none-softfloat
                  rustup component add llvm-tools-preview
                  cargo install cargo-binutils
            - name: Run
              run: BSP=rpi4 make
