name: Integration Tests

on:
    push:
        branches:
            - master
        paths-ignore:
            - "utils/**"
            - "doc/**"
            - "docker/**"
    pull_request:
        branches:
            - master
        paths-ignore:
            - "utils/**"
            - "doc/**"
            - "docker/**"
    schedule:
        - cron: "0 5 * * *"

jobs:
    build:
        name: Run integration tests
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
            - name: Install QEMU
              run: sudo apt-get update && sudo apt-get install --yes qemu-system-arm
            - name: Set up Rust tools
              run: |
                  rustup target add aarch64-unknown-none-softfloat
                  rustup component add llvm-tools-preview
                  cargo install cargo-binutils
            - name: Run stable kernel tests
              run: BSP=rpi3 make test
